# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ce368eb6490733e24b6c3b7a8b29d52549282004c1b0643c55cd345810f1f2f76fd8a219b86c4d0a747c79dcef90260a3efcb1d06c51e6b4139975133b4cccc

test:
  secret_key_base: 8008fc0c00fc6ff4b347e41c92a10da487eabb0277e5add0455ec33ddcaeb99d949145ca3276ff83500b6eace09e7aa2467931aa1d3fb8487acec9daaf555ef2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
